import { chromium, devices } from '@playwright/test';
const b = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE });
const dir = '/tmp/claude-0/-home-user-adhd-med/61048ee9-e9d6-5fda-a715-7b2c23961c24/scratchpad';
const base = 'http://localhost:4173/adhd-med/';
const ctx = await b.newContext({ ...devices['iPhone 14'], defaultBrowserType: 'chromium' });
const p = await ctx.newPage();
await p.goto(base);
await p.getByRole('dialog').getByRole('button', { name: 'Begin', exact: true }).click();
await p.goto(`${base}#/lab`);
await p.waitForTimeout(500);
await p.screenshot({ path: `${dir}/v3-lab.png` });
await p.goto(`${base}#/logos`);
await p.waitForTimeout(600);
await p.screenshot({ path: `${dir}/v3-logos.png` });
await p.goto(`${base}#/dj`);
await p.getByRole('button', { name: 'Play something' }).click();
await p.waitForTimeout(2400);
await p.locator('#mini').click();
await p.waitForTimeout(700);
await p.screenshot({ path: `${dir}/v3-session.png` });
await b.close();
